Repository atomic-blend/app, pull requests merged in 2025-05, with the labels that each got.

#73 fix: for the text becoming invisible when using phone in dark mode in Android
  .github/workflows/build-test.yml
  lib/components/forms/task_date_picker_modal/duration_picker.dart
  lib/components/forms/task_date_picker_modal/single_date_picker.dart
Labels: run-ci

#75 fix: add validation on password length in register
  lib/i18n/en.i18n.json
  lib/i18n/fr.i18n.json
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_fr.g.dart
  lib/pages/auth/screens/register_password.dart
Labels: bug

#77 fix: email validation
  lib/i18n/en.i18n.json
  lib/i18n/fr.i18n.json
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_fr.g.dart
  lib/pages/account/profile_edit.dart
Labels: bug

#80 fix: support Tablets as desktop devices
  fastlane/fastlane/report.xml
  lib/main.dart
  lib/pages/app_wrapper.dart
  lib/utils/shortcuts.dart
  pubspec.yaml
Labels: enhancement

#81 fix: Tablets as Desktop
  fastlane/fastlane/report.xml
  lib/main.dart
  lib/pages/app_wrapper.dart
  lib/utils/shortcuts.dart
  pubspec.yaml
Labels: enhancement

#83 fix: support for linux and windows
  lib/main.dart
  lib/services/notifications/fcm_service.dart
  linux/CMakeLists.txt
  linux/my_application.cc
  windows/runner/main.cpp
Labels: enhancement

#84 fix: support for windows and linux
  lib/main.dart
  lib/services/notifications/fcm_service.dart
  linux/CMakeLists.txt
  linux/my_application.cc
  windows/runner/main.cpp
Labels: enhancement

#85 feat: task priority
  ios/Runner.xcodeproj/project.pbxproj
  lib/components/buttons/task_item.dart
  lib/components/dialogs/priority_picker.dart
  lib/entities/tasks/tasks.entity.dart
  lib/entities/tasks/tasks.entity.freezed.dart
  lib/entities/tasks/tasks.entity.g.dart
  lib/i18n/en.i18n.json
  lib/i18n/fr.i18n.json
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_fr.g.dart
  lib/pages/calendar/calendar.dart
  lib/pages/tasks/add_task_modal.dart
  lib/pages/tasks/task_detail.dart
Labels: enhancement

#88 feat: notes in task
  lib/app.dart
  lib/components/buttons/task_item.dart
  lib/i18n/en.i18n.json
  lib/i18n/fr.i18n.json
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_fr.g.dart
  lib/pages/tasks/task_detail.dart
  pubspec.yaml
Labels: enhancement

#90 fix: enhancements of the UI on mobile and desktop
  lib/components/app/bottom_navigation.dart
  lib/components/app/side_menu_item.dart
  lib/components/app/side_navigation.dart
  lib/components/buttons/task_item.dart
  lib/components/dialogs/priority_picker.dart
  lib/components/forms/search_bar.dart
  lib/components/widgets/elevated_container.dart
  lib/i18n/en.i18n.json
  lib/i18n/fr.i18n.json
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_fr.g.dart
  lib/pages/app_wrapper.dart
  lib/pages/calendar/calendar.dart
  lib/pages/calendar/calendar_settings.dart
  lib/pages/calendar/device_event_detail.dart
  lib/pages/eiseinhower/eisenhower.dart
  lib/pages/more_apps/more_apps.dart
  lib/pages/tasks/add_task_modal.dart
  lib/pages/tasks/filtered_view.dart
  lib/pages/tasks/overview.dart
  lib/pages/tasks/tags.dart
  lib/pages/tasks/task_detail.dart
  lib/utils/app_theme.dart
  lib/utils/constants.dart
Labels: enhancement

#91 fix: some ui bugs on habit
  lib/components/buttons/date_picker_button.dart
  lib/components/forms/app_text_form_field.dart
  lib/components/forms/task_date_picker_modal/duration_picker.dart
  lib/components/widgets/elevated_container.dart
  lib/pages/calendar/calendar.dart
  lib/pages/habits/add_habits_modal.dart
  lib/pages/habits/habits.dart
  lib/pages/more_apps/more_apps.dart
  lib/pages/tasks/filtered_view.dart
  lib/pages/tasks/overview.dart
  lib/pages/tasks/tags.dart
Labels: bug
